
stages:
  - test
  - build
  - publish

include:
  # Unit testing
  - component: $CI_SERVER_FQDN/bioinformatics/pipelines/python/unittesting@0.2.0
    inputs:
      stage: test
  # Build packages
  - component: $CI_SERVER_FQDN/bioinformatics/pipelines/python/build_package@0.2.0
    inputs:
      stage: build
  # Publish packages
  - component: $CI_SERVER_FQDN/bioinformatics/pipelines/python/publish_package@0.2.0
    inputs:
      job_name: publish_irods_package
      stage: publish

# Define rules for the job
publish_irods_package:
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+/
