
stages:
  - test
  - build
  - internal_publish
  - release_publish

include:
  # Unit testing
  - component: $CI_SERVER_FQDN/bioinformatics/pipelines/python/unittesting@0.2.1
    inputs:
      stage: test
  # Build and publish the package
  - component: $CI_SERVER_FQDN/bioinformatics/pipelines/python/build_package@0.2.1
    inputs:
      job_name: build_package
      stage: build
  - component: $CI_SERVER_FQDN/bioinformatics/pipelines/python/publish_package@0.2.1
    inputs:
      job_name: publish_package_rc
      stage: internal_publish
  # Build and release package
  - component: $CI_SERVER_FQDN/bioinformatics/pipelines/python/publish_package@0.2.1
    inputs:
      job_name: publish_package_pr
      username: oauth2
      password: $PUBLISH_TOKEN
      publish_url: ${CI_API_V4_URL}/projects/4682/packages/pypi
      stage: release_publish

# Define rules for the job
build_package:
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(-rc\.\d+)?$/
publish_package_rc:
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+-rc\.\d+$/
publish_package_pr:
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/